const pages=[...document.querySelectorAll(".page")],dots=[...document.querySelectorAll(".step-dot")],prevBtn=document.getElementById("prevBtn"),nextBtn=document.getElementById("nextBtn"),pageLabel=document.getElementById("pageLabel");let currentPage=0;
function showPage(i){currentPage=Math.max(0,Math.min(i,pages.length-1));pages.forEach((p,n)=>p.classList.toggle("active",n===currentPage));dots.forEach((d,n)=>d.classList.toggle("active",n===currentPage));prevBtn.disabled=currentPage===0;nextBtn.textContent=currentPage===pages.length-1?"Restart ↺":"Next →";pageLabel.textContent=`${currentPage+1} of ${pages.length}`}
prevBtn.addEventListener("click",()=>showPage(currentPage-1));nextBtn.addEventListener("click",()=>currentPage===pages.length-1?showPage(0):showPage(currentPage+1));

const rightPole=document.getElementById("rightPole"),distance=document.getElementById("distance"),rightMagnet=document.getElementById("rightMagnet"),interactionStatus=document.getElementById("interactionStatus"),statusExplanation=document.getElementById("statusExplanation"),forceReadout=document.getElementById("forceReadout"),leftArrow=document.getElementById("leftArrow"),rightArrow=document.getElementById("rightArrow"),attractArrows=document.getElementById("attractArrows");
function updateDemo(){const pole=rightPole.value,d=Number(distance.value),repel=pole==="S",rightPos=20+d*.45;rightMagnet.style.right=`${rightPos}px`;rightMagnet.src=pole==="S"?"assets/bar-magnet-sn.svg":"assets/bar-magnet-ns.svg";const strength=Math.round(100*(1-(d-20)/160)),word=strength>66?"strong":strength>33?"medium":"weak";if(repel){interactionStatus.textContent="REPULSION";interactionStatus.style.color="#b64242";statusExplanation.textContent="The facing poles are the same (S–S), so the magnets push away from each other.";leftArrow.style.display="block";rightArrow.style.display="block";attractArrows.style.display="none";forceReadout.innerHTML=`<b>Repulsive force:</b> ${word}. Moving the magnets closer makes the force stronger.`}else{interactionStatus.textContent="ATTRACTION";interactionStatus.style.color="#25845d";statusExplanation.textContent="The facing poles are different (S–N), so the magnets pull toward each other.";leftArrow.style.display="none";rightArrow.style.display="none";attractArrows.style.display="flex";forceReadout.innerHTML=`<b>Attractive force:</b> ${word}. Moving the magnets closer makes the force stronger.`}const s=.75+strength/160;leftArrow.style.transform=`scale(${s})`;rightArrow.style.transform=`scale(${s})`;attractArrows.style.transform=`scale(${s})`}
rightPole.addEventListener("change",updateDemo);distance.addEventListener("input",updateDemo);updateDemo();

let score=0;document.querySelectorAll(".question-card").forEach(card=>{let answered=false;const answer=card.dataset.answer,feedback=card.querySelector(".feedback");card.querySelectorAll("button").forEach(btn=>btn.addEventListener("click",()=>{if(answered)return;answered=true;const choice=btn.dataset.choice;if(choice===answer){btn.classList.add("correct");feedback.textContent="Correct!";feedback.style.color="#25845d";document.getElementById("score").textContent=++score}else{btn.classList.add("incorrect");feedback.textContent=`It will ${answer}.`;feedback.style.color="#b64242";card.querySelector(`[data-choice="${answer}"]`).classList.add("correct")}}))});

const challengeLeft=document.getElementById("challengeLeft"),challengeRight=document.getElementById("challengeRight"),challengeLeftInner=document.getElementById("challengeLeftInner"),challengeLeftOuter=document.getElementById("challengeLeftOuter"),challengeRightInner=document.getElementById("challengeRightInner"),challengeRightOuter=document.getElementById("challengeRightOuter"),interactionSymbol=document.getElementById("interactionSymbol"),challengeFeedback=document.getElementById("challengeFeedback"),challengeInstruction=document.getElementById("challengeInstruction");let target="repel";
function setPole(el,p){el.textContent=p;el.className=`pole ${p==="N"?"north":"south"}`}
function updateChallengeVisual(){const l=challengeLeft.value,r=challengeRight.value;setPole(challengeLeftInner,l);setPole(challengeLeftOuter,l==="N"?"S":"N");setPole(challengeRightInner,r);setPole(challengeRightOuter,r==="N"?"S":"N");interactionSymbol.textContent=l===r?"↔":"→←"}
challengeLeft.addEventListener("change",updateChallengeVisual);challengeRight.addEventListener("change",updateChallengeVisual);
document.getElementById("checkChallenge").addEventListener("click",()=>{const actual=challengeLeft.value===challengeRight.value?"repel":"attract";if(actual===target){challengeFeedback.innerHTML=`<b>Correct.</b> ${challengeLeft.value} facing ${challengeRight.value} will ${actual}.`;challengeFeedback.style.borderColor="#7bc8a5"}else{challengeFeedback.innerHTML=`<b>Not yet.</b> Those poles will ${actual}. Change one or both poles and try again.`;challengeFeedback.style.borderColor="#e3a0a0"}});
document.getElementById("newChallenge").addEventListener("click",()=>{target=target==="repel"?"attract":"repel";challengeInstruction.innerHTML=`Make the two magnets <b>${target}</b>.`;challengeFeedback.textContent="";challengeFeedback.style.borderColor=""});
updateChallengeVisual();showPage(0);
